name: Jekyll Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Install Bundler 2.4.22
        run: gem install bundler -v 2.4.22

      - name: Bundler Cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Validate bio.json File
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\bio.json$"

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Build & Deploy to GitHub Pages
        uses: helaili/jekyll-action@2.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
